export const options = [
  { label: "All", icon: "" },
  { label: "Aluminium packaging", icon: "aluminium@2x" },
  { label: "Batteries", icon: "batterien@2x" },
  {
    label: "Electric Equipment Office + Entertainment",
    icon: "elektrogeraete@2x",
  },
  {
    label: "Electric Household Appliances",
    icon: "elektrogeraete_haushalt@2x",
  },
  { label: "Glass", icon: "glas@2x" },
  { label: "PET drink bottles", icon: "pet@2x" },
  {
    label: "Sheet Steel/Tinplate Packaging",
    icon: "stahlblech@2x",
  },
  { label: "Textile and Shoes", icon: "textilien@2x" },
  { label: "Waste Oil", icon: "altoel@2x" },
  { label: "Aluminium Capsules", icon: "kaffee@2x" },
  { label: "Beverage Capsules", icon: "getraenkekartons@2x" },
  { label: "Bicycles", icon: "velos@2x" },
  { label: "Biogenous Waste", icon: "biogene@2x" },
  { label: "Bulky Items", icon: "sperrgut@2x" },
  { label: "Car batteries", icon: "auto@2x" },
  { label: "Cardboard", icon: "karton@2x" },
  { label: "CDs + DVDs", icon: "cd@2x" },
  { label: "Corks", icon: "korken@2x" },
  { label: "EPS", icon: "eps@2x" },
  { label: "Fluorescent Lamps", icon: "leuchtstofflampen@2x" },
  { label: "Green waste", icon: "gruengut@2x" },
  { label: "Household waste", icon: "hauskehricht@2x" },
  { label: "Inert Substances", icon: "inertstoffe@2x" },
  { label: "Ink Cartridges", icon: "tintenpatrone@2x" },
  {
    label: "Landfill Refuse (mineral waste)",
    icon: "grubengut@2x",
  },
  { label: "Metals", icon: "metalle@2x" },
  { label: "Paper", icon: "papier@2x" },
  { label: "PE Dairy Produce Bottles", icon: "pe@2x" },
  { label: "Plastic bottles", icon: "kunststoff@2x" },
  {
    label: "Plastic (except EPS and PET)",
    icon: "kunststoffe@2x",
  },
  { label: "Second hand shop", icon: "brockenhaeuser@2x" },
  { label: "Special Waste (chemicals)", icon: "sonderabfaelle@2x" },
  { label: "Tires", icon: "pneus@2x" },
  { label: "Toner Cartridge", icon: "tonerkartusche@2x" },
  {
    label: "Unbroken Glass (whole bottles)",
    icon: "ganzglas@2x",
  },
  { label: "Water Filter Cartridges", icon: "wasserfilterkartusche@2x" },
  { label: "Wood", icon: "altholz@2x" },
];
